What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

What Can Pandas Do?
Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?
What is average value?
Max value?
Min value?
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

installed it using this command
pip install pandas

In [2]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)
print(myvar)
print(pd.__version__) # checking pandas version

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
2.3.2

What is a Series?
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.

Labels
If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.
With the index argument, you can name your own labels.


Key/Value Objects as Series
You can also use a key/value object, like a dictionary, when creating a Series.
Note: The keys of the dictionary become the labels.

In [7]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar[0]) # you can access rows and columns using labels
indexargument= pd.Series(a,index=["x","y","z"]) # you can also specify index
print(indexargument)
print(indexargument['z']) # you can access values with index
print(myvar)

# using key value pair like dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"]) #To select only some of the items in the dictionary, use the index argument and specify only the items you want to include in the Series.
print(myvar["day1"])


print(myvar)

1
x    1
y    7
z    2
dtype: int64
2
0    1
1    7
2    2
dtype: int64
420
day1    420
day2    380
dtype: int64

DataFrames
Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.

Locate Row
Pandas use the loc attribute to return one or more specified row(s)

In [10]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

#refer to the row index:
print(df.loc[0]) #Note: This example returns a Pandas Series.

#use a list of indexes:
print(df.loc[[0, 1]]) #Note: When using [], the result is a Pandas DataFrame.

df2 = pd.DataFrame(data, index = ["day1", "day2", "day3"]) # name index like in series 
print(df2)
#refer to the named index:
print(df2.loc["day2"])


print(df)

calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40
      calories  duration
day1       420        50
day2       380        40
day3       390        45
calories    380
duration     40
Name: day2, dtype: int64
   calories  duration
0       420        50
1       380        40
2       390        45

Read CSV Files
A simple way to store big data sets is to use CSV files (comma separated files).

CSV files contains plain text and is a well know format that can be read by everyone including Pandas

In [31]:
import pandas as pd
df = pd.read_csv("data.csv")
# df.head() # return only first five rows if you not pass any arguments
# # df.tail() # return only last five rows if you not pass any arguments
# print(df) # if you use to display data its only show first and last five dataset 
# print(df.to_string()) # if you want to show full data set you can use to_string() method
df[['Brand']] # show column Name with bold 
#df['Brand'] # selecting and indexing selecting single column \

df[['Brand','Sale_ID']] # selecting mulitple columns
#df['Brand','Sale_ID'] # its give error you can not access muliple column using this syntax
df.iloc[0] # return 1 row of the data set 
df.iloc[0:1] # return 1 row of the data set with bold keyword 
df.loc[0,'Brand'] # row 0 , column Name
df.iloc[0,2] # row 0 , column index 2
df[df['Price_USD'] > 80] # apply condition 
df[(df['Price_USD'] > 80 ) & (df["Country"] == "UK")] # apply condition

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
9,10,Huawei,Huawei Model 6,UK,512GB,Gold,921,2,1842,4.8,Cash,3,2025
27,28,Huawei,Huawei Model 17,UK,256GB,Green,1395,6,8370,4.5,Credit Card,12,2025
53,54,Huawei,Huawei Model 8,UK,512GB,Silver,1409,1,1409,4.1,Installments,7,2025
74,75,Motorola,Motorola Model 6,UK,256GB,Green,754,8,6032,4.9,Credit Card,1,2025
77,78,Realme,Realme Model 5,UK,256GB,Blue,908,7,6356,4.6,Credit Card,2,2025
98,99,Google,Google Model 15,UK,512GB,Black,383,12,4596,4.8,Cash,7,2025
130,131,Google,Google Model 16,UK,512GB,Green,1088,7,7616,3.6,Online Payment,3,2025
139,140,OnePlus,OnePlus Model 7,UK,128GB,Gold,1482,10,14820,4.6,Cash,6,2025
149,150,Oppo,Oppo Model 7,UK,256GB,Gold,1118,7,7826,4.7,Cash,5,2025
154,155,Oppo,Oppo Model 7,UK,256GB,Green,1240,2,2480,4.1,Installments,8,2025
166,167,Oppo,Oppo Model 3,UK,512GB,Green,460,12,5520,3.6,Installments,11,2025
179,180,Realme,Realme Model 12,UK,512GB,Gold,477,7,3339,4.5,Credit Card,6,2025
186,187,Apple,Apple Model 13,UK,256GB,Blue,1279,16,20464,4.9,Debit Card,3,2025
189,190,Realme,Realme Model 8,UK,256GB,Green,361,1,361,3.8,Credit Card,8,2025
204,205,Apple,Apple Model 14,UK,128GB,White,322,6,1932,4.0,Installments,9,2025
206,207,Samsung,Samsung Model 19,UK,64GB,Silver,1198,6,7188,3.8,Cash,6,2025
225,226,Motorola,Motorola Model 8,UK,512GB,Gold,1115,15,16725,4.2,Credit Card,12,2025
231,232,Oppo,Oppo Model 3,UK,64GB,White,1084,3,3252,3.6,Installments,12,2025
235,236,Huawei,Huawei Model 12,UK,128GB,Silver,917,16,14672,3.6,Cash,8,2025
265,266,Motorola,Motorola Model 20,UK,64GB,Silver,1087,18,19566,3.5,Online Payment,9,2025
282,283,Apple,Apple Model 18,UK,128GB,Gold,1406,9,12654,3.1,Online Payment,9,2025
289,290,Oppo,Oppo Model 19,UK,64GB,White,1022,19,19418,4.2,Credit Card,5,2025
305,306,Google,Google Model 6,UK,256GB,Silver,480,18,8640,5.0,Debit Card,9,2025
310,311,Google,Google Model 12,UK,64GB,Gold,1058,4,4232,4.5,Debit Card,2,2025
315,316,Motorola,Motorola Model 18,UK,256GB,Black,539,1,539,3.7,Online Payment,10,2025
328,329,Oppo,Oppo Model 3,UK,64GB,Gold,1215,6,7290,4.6,Debit Card,6,2025
339,340,Apple,Apple Model 19,UK,128GB,White,1236,13,16068,4.6,Installments,6,2025
346,347,Motorola,Motorola Model 14,UK,128GB,White,528,20,10560,3.4,Installments,8,2025
351,352,OnePlus,OnePlus Model 7,UK,128GB,Black,1481,12,17772,3.1,Installments,10,2025
353,354,Google,Google Model 18,UK,128GB,Blue,1412,5,7060,3.8,Installments,2,2025
357,358,Apple,Apple Model 3,UK,64GB,White,826,9,7434,3.5,Installments,4,2025
368,369,Samsung,Samsung Model 5,UK,256GB,Black,715,4,2860,4.6,Debit Card,8,2025
369,370,Vivo,Vivo Model 7,UK,128GB,Gold,1310,1,1310,4.2,Cash,8,2025
371,372,Google,Google Model 17,UK,64GB,Gold,1284,17,21828,3.6,Online Payment,9,2025
384,385,Huawei,Huawei Model 5,UK,256GB,Silver,384,14,5376,4.0,Debit Card,2,2025
391,392,Samsung,Samsung Model 5,UK,128GB,Gold,1000,9,9000,4.7,Online Payment,8,2025
396,397,Xiaomi,Xiaomi Model 19,UK,64GB,White,1449,9,13041,3.8,Installments,7,2025
401,402,Oppo,Oppo Model 14,UK,64GB,Gold,569,9,5121,4.5,Debit Card,7,2025
407,408,Huawei,Huawei Model 5,UK,128GB,Blue,713,15,10695,4.8,Debit Card,2,2025
409,410,Realme,Realme Model 17,UK,128GB,Green,1227,6,7362,3.5,Credit Card,8,2025
410,411,Xiaomi,Xiaomi Model 17,UK,64GB,Gold,648,19,12312,4.4,Credit Card,4,2025
411,412,Motorola,Motorola Model 7,UK,128GB,Gold,574,5,2870,4.8,Debit Card,9,2025
431,432,Oppo,Oppo Model 7,UK,512GB,Silver,336,20,6720,4.8,Cash,8,2025
447,448,Xiaomi,Xiaomi Model 3,UK,512GB,Blue,1109,16,17744,4.1,Credit Card,8,2025
456,457,Motorola,Motorola Model 15,UK,64GB,Silver,538,3,1614,4.4,Online Payment,5,2025
461,462,Oppo,Oppo Model 5,UK,64GB,Green,772,14,10808,4.5,Cash,3,2025
478,479,Vivo,Vivo Model 8,UK,256GB,Black,729,6,4374,4.4,Online Payment,5,2025
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

In [37]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ali", None],
    "Marks": [85, 90, 75, 85, None],
    "City": ["Lahore", "Karachi", "Islamabad", None, "Karachi"]
}

df = pd.DataFrame(data)
print(df["Name"].unique())
print(df["Name"].value_counts())
print(df.columns)
print(df.index)
print(df)

['Ali' 'Sara' 'Ahmed' None]
Name
Ali      2
Sara     1
Ahmed    1
Name: count, dtype: int64
Index(['Name', 'Marks', 'City'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara   90.0    Karachi
2  Ahmed   75.0  Islamabad
3    Ali   85.0       None
4   None    NaN    Karachi

In [43]:
df.sort_values('Marks') # sort values according to Marks 
df.sort_values('Marks', ascending=False) # descending order
df.sort_values(['City','Marks'])
df.isnull() # return false if the value is not null other wise return true
df.isnull().sum() # return how many is null in the columns

Name     1
Marks    1
City     1
dtype: int64

In [49]:
df.dropna() # remove None row from the data set 
df.fillna(10,inplace=True) # replace None values with specific value that you provide , and inplace change original data set 
print(df)

    Name  Marks       City
0    Ali   85.0     Lahore
1   Sara   90.0    Karachi
2  Ahmed   75.0  Islamabad
3    Ali   85.0         10
4     10   10.0    Karachi

In [51]:
df['City'].replace('Lahore','LHR') # replace one value
df.replace({'Lahore':'LHR' , 'Karachi': 'KHI'}) # replace more than one value

    Name  Marks       City
0    Ali   85.0        LHR
1   Sara   90.0        KHI
2  Ahmed   75.0  Islamabad
3    Ali   85.0         10
4     10   10.0        KHI

In [54]:
df.drop('City',axis=1) # Drop column when you drop column also specified the axis 1 which refer to the column 
df.drop(0) # drop row with zero index

    Name  Marks       City
1   Sara   90.0    Karachi
2  Ahmed   75.0  Islamabad
3    Ali   85.0         10
4     10   10.0    Karachi